# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Add support to default build

name: Continuous Integration with Gradle

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - bugfix/**
      - feature/**

jobs:

  build-ci:
    name: Build gRPC Backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Java JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 8
          architecture: x64
          
      - name: get adempiere source
        run: |
          download_repo="https://github.com/erpcya/adempiere/releases/download/3.9.3-rs-4.3/Adempiere_393LTS.tar.gz"
          wget $download_repo -c -O Adempiere.tar.gz

      - name: uncompress file
        run: tar -xzf Adempiere.tar.gz
      - name: create dependences folder
        run: mkdir dependences
      - name: move dependences
        run: mv Adempiere/lib/*.jar dependences/
      - name: move packages
        run: mv Adempiere/packages/*/lib/*.jar dependences/

      - name: Build with Gradle
        run: gradle build
