# This workflow will build a Java project with Gradle
# This file was contributed by ysenih@erpya.com from ERP Consultores y Asociados, C.A
# This file was contributed by EdwinBetanc0urt@outlook.com https://github.com/EdwinBetanc0urt
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration with Gradle

permissions:
  contents: write # to upload release assets
  packages: write # to publish packages

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

  pull_request:
    branches:
      - main
      - master
      - develop
      - experimental
      - test/**
      - bugfix/**
      - feature/**
      - hotfix/**
      - test/**
    paths-ignore:
      - README.md
      - README.es.md
      - docker/*

jobs:

  build-ci:
    name: Build ADempiere gRPC Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Setup Java JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: 17
          architecture: x64

      - name: Setup Gradle 9
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 9.1.0 # current

      - name: Run Create Release
        run: gradle createRelease --warning-mode all --stacktrace
        env:
          GITHUB_DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          GITHUB_DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Upload descriptor file artifact
        uses: actions/upload-artifact@v5
        with:
          name: adempiere-grpc-server.dsc
          path: build/descriptors/adempiere-grpc-server.dsc
          retention-days: 1

      - name: Upload dist app zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: adempiere-grpc-server.zip
          path: build/release/adempiere-grpc-server.zip
          retention-days: 1
